# H2 en modo archivo (persistente en PVC)
spring.datasource.url=jdbc:h2:file:/data/oauth2db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never

# Seguridad
spring.h2.console.enabled=false

# OAuth2 (valores vienen de variables de entorno)
oauth2.client-id=${OAUTH_CLIENT_ID}
oauth2.client-secret=${OAUTH_CLIENT_SECRET}
oauth2.redirect-uri=${OAUTH_REDIRECT_URI}

oauth2.access-token-validity-seconds=86400
oauth2.refresh-token-validity-seconds=129600

# Clave JWT segura (viene de Secret)
oauth2.jwt-signing-key=${JWT_SIGNING_KEY}
