server.port=8080

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Base de datos H2 en modo archivo (persistente)
spring.datasource.url=jdbc:h2:file:./data/oauth2db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MUY IMPORTANTE:
# Hace que Hibernate cree las tablas ANTES de ejecutar data.sql o CommandLineRunner
spring.jpa.defer-datasource-initialization=true

# Subida de ficheros
upload.root-location=upload-dir

# JSON
spring.jackson.mapper.default-view-inclusion=true

# OAuth2 clásico
oauth2.client-id=proveedor-oauth
oauth2.client-secret=123456
oauth2.redirect-uri=http://localhost:8080/login.html

# Tokens
oauth2.access-token-validity-seconds=86400
oauth2.refresh-token-validity-seconds=129600
